Chore/db drizzle schema
activecourses/disworse pull request #25
Opened 2024-09-25 04:04 UTC by bassiounix

initial schema.

some functionalities are missing on the drizzle side .. future work arounds are needed

2024-09-26 03:23 UTC, G0maa requested changes
3ash ya5oia

2024-09-26 14:49 UTC, bassiounix commented on .gitignore
> +migrations/
this was a mistake, on it

2024-09-26 14:51 UTC, bassiounix commented on apps/api/drizzle.config.ts
> +        url: String(process.env.DATABASE_URL),
An example file of .env is ok for the whole suite of configs

2024-09-26 14:53 UTC, bassiounix commented on apps/api/src/drizzle/drizzle.module.ts
> +        DrizzlePGModule.registerAsync({
We could, however this one made the heavy lifting for us, as in, we would do the same thing as the package did.
It gives a wrapper (adapter) around Drizzle to use it in the Nest style of doing things (& Nest IoC).

2024-09-26 14:57 UTC, bassiounix commented on apps/api/src/drizzle/schema/server.ts
> +    owner_id: integer("owner_id").notNull(), // TODO: figure out the right relation for the owner (the egg and the chicken dilemma)
The problem is wether the owner_id is a server user or a regular user (refer back to ERD)
as in, 2 tables are dependent on each other, so this gives an error in TypeScript on my side

2024-09-26 16:12 UTC, alikehel commented on apps/api/package.json
> +        "dev": "nest start --exec \"node --env-file=../../.env.backend\" --watch",
Correct this.

2024-09-26 16:14 UTC, alikehel commented on apps/api/package.json
> +        "nestjs-zod": "^3.0.0",
Deprecated package.

2024-09-26 16:15 UTC, alikehel commented on apps/api/src/drizzle/drizzle.module.ts
> +        DrizzlePGModule.registerAsync({
> Are we really absolutely sure about this module?
> 
> Can't we code it ourselves instead? @abdo0nasser @alikehel @bassiounix

I'm not a fan of using it.

2024-09-26 16:21 UTC, alikehel commented
Dont forget to pull from main and then
1. resolve any merge conflict other than the lockfile
2. run `pnpm i`
3. run `git add --update`
4. run `git commit`
5. close the opened file
6. push ur changes

2024-09-26 17:12 UTC, G0maa commented on apps/api/src/drizzle/schema/server.ts
> +    owner_id: integer("owner_id").notNull(), // TODO: figure out the right relation for the owner (the egg and the chicken dilemma)
@bassiounix Just user, when he creates the server he is then added as a member too.

2024-09-26 17:12 UTC, G0maa commented on apps/api/src/drizzle/drizzle.module.ts
> +        DrizzlePGModule.registerAsync({
@bassiounix 
I still do not get what's the difference between it, and creating a custom global injectable drizzle service :thinking:

2024-09-26 17:13 UTC, G0maa commented on apps/api/drizzle.config.ts
> +        url: String(process.env.DATABASE_URL),
@bassiounix yes, it is. But later we will have a database for testing that runs on e.g. a different port. Which will load a different `.env` file.

2024-09-26 17:13 UTC, G0maa commented on .gitignore
> +migrations/
@bassiounix resolve if fixed

2024-09-27 02:37 UTC, bassiounix commented on apps/api/drizzle.config.ts
> +        url: String(process.env.DATABASE_URL),
Then the only change will be the env variable value, that is, found in the new env files

Also dotenv is in use for this particular case, and settings can be applied easily

2024-09-27 02:38 UTC, bassiounix commented on apps/api/src/drizzle/drizzle.module.ts
> +        DrizzlePGModule.registerAsync({
Nothing different other than the work is already done in the package, as in every other package out there!

2024-09-27 02:41 UTC, bassiounix commented on apps/api/src/drizzle/schema/server.ts
> +    owner_id: integer("owner_id").notNull(), // TODO: figure out the right relation for the owner (the egg and the chicken dilemma)
Yes but not prior to that (order of operations)

Fixed anyway

2024-09-27 07:24 UTC, G0maa commented on apps/api/src/drizzle/drizzle.module.ts
> +        DrizzlePGModule.registerAsync({
@bassiounix Did you try/research a different approach? This [one](https://wanago.io/2024/05/20/api-nestjs-drizzle-orm-postgresql/) in particular. My problem with this package is it's not an official integration, and isn't widely used.

2024-09-27 14:50 UTC, bassiounix commented on apps/api/package.json
> +        "dev": "nest start --exec \"node --env-file=../../.env.backend\" --watch",
done

2024-09-27 14:50 UTC, bassiounix commented on apps/api/package.json
> +        "nestjs-zod": "^3.0.0",
done

2024-09-27 15:17 UTC, bassiounix commented on apps/api/src/drizzle/drizzle.module.ts
> +        DrizzlePGModule.registerAsync({
still the same things but written in a package .. that's all really

2024-09-27 18:29 UTC, merged