feat: add sidebar with dashboard, servers and notifications
activecourses/disworse pull request #27
Opened 2024-09-25 18:32 UTC by GoatMoaz

This pull request introduces a sidebar layout feature, including the following changes:

- Added a sidebar with navigation options for the dashboard, servers, and notifications.
- Implemented the basic structure to organize and manage these sections within the application.

Commit: 21b3e6bd3c81e37559f95cd219736990023a4bb3

Additionally, here is a screenshot of the layout with the sidebar:
![image](https://github.com/user-attachments/assets/df78deeb-dea3-446b-ab0b-0730811dabde)

2024-09-25 22:40 UTC, alikehel requested changes

2024-09-25 22:40 UTC, alikehel commented on apps/web/src/components/layouts/Sidebar.module.css
- Why not use tailwind?

2024-09-25 22:40 UTC, alikehel commented on apps/web/src/components/layouts/Sidebar.tsx
- Only use small letters in file names (seperated by hyphens if more than one word).
- Component stays the same don't change it.

2024-09-25 22:40 UTC, alikehel commented on pnpm-lock.yaml
- Remove this file and `pnpm i` again.
- I don't understand how is it changed and package.json is the same xD.

2024-09-25 23:59 UTC, GoatMoaz commented on apps/web/src/components/layouts/Sidebar.module.css
Couldn't find a default tailwind class but I will try to configure it in tailwind.config.js

2024-09-26 00:00 UTC, GoatMoaz commented on pnpm-lock.yaml
Same lol

2024-09-26 01:23 UTC, merged